"""Phase 0: Gemma-3-270M draft + Gemma-3-12B target, both on MLX GPU.

Tests mlx-lm's built-in speculative decoding across diverse prompts.
Measures acceptance rate and wall-clock speedup.
"""
import time
import statistics
from mlx_lm import load, stream_generate
from mlx_lm.sample_utils import make_sampler

TARGET = "mlx-community/gemma-3-12b-it-4bit"
DRAFT = "mlx-community/gemma-3-270m-it-bf16"

PROMPTS = [
    "The capital of France is",
    "1 + 1 equals",
    "def fibonacci(n):",
    "The Pythagorean theorem states that",
    "In machine learning, gradient descent is",
    "The speed of light in vacuum is approximately",
    "To make a good cup of coffee, first",
    "The largest planet in our solar system is",
    "Write a Python function that reverses a string.",
    "Explain photosynthesis in one paragraph:",
]

MAX_TOKENS = 80
NUM_DRAFT = 4


def main():
    print("Loading target (Gemma-3-12B 4bit)...", flush=True)
    t0 = time.perf_counter()
    target_model, tokenizer = load(TARGET)
    print(f"  loaded in {time.perf_counter() - t0:.1f}s", flush=True)

    print("Loading draft (Gemma-3-270M bf16)...", flush=True)
    t0 = time.perf_counter()
    draft_model, draft_tok = load(DRAFT)
    print(f"  loaded in {time.perf_counter() - t0:.1f}s", flush=True)

    # Verify tokenizers match
    test_prompt = "The quick brown fox"
    t1 = tokenizer.encode(test_prompt)
    t2 = draft_tok.encode(test_prompt)
    assert t1 == t2, f"Tokenizer mismatch: target={t1} draft={t2}"
    print(f"Tokenizers match (test encode: {t1})\n", flush=True)

    sampler = make_sampler(temp=0.0)

    # Warmup on one prompt
    print("Warming up...", flush=True)
    for _ in stream_generate(target_model, tokenizer, "hello", max_tokens=5,
                              draft_model=draft_model, num_draft_tokens=NUM_DRAFT,
                              sampler=sampler):
        pass
    for _ in stream_generate(target_model, tokenizer, "hello", max_tokens=5, sampler=sampler):
        pass
    print("Warmup done.\n", flush=True)

    results = []
    for i, prompt in enumerate(PROMPTS):
        print(f"[{i+1}/{len(PROMPTS)}] {prompt!r}", flush=True)

        # Baseline: target only
        t0 = time.perf_counter()
        base_tokens = []
        for resp in stream_generate(target_model, tokenizer, prompt,
                                     max_tokens=MAX_TOKENS, sampler=sampler):
            base_tokens.append(resp.token)
        t_base = time.perf_counter() - t0
        base_tps = len(base_tokens) / t_base

        # SD: draft + target
        t0 = time.perf_counter()
        sd_tokens = []
        from_draft_flags = []
        for resp in stream_generate(target_model, tokenizer, prompt,
                                     max_tokens=MAX_TOKENS, sampler=sampler,
                                     draft_model=draft_model, num_draft_tokens=NUM_DRAFT):
            sd_tokens.append(resp.token)
            from_draft_flags.append(getattr(resp, 'from_draft', False))
        t_sd = time.perf_counter() - t0
        sd_tps = len(sd_tokens) / t_sd

        n_from_draft = sum(from_draft_flags)
        # Acceptance rate: fraction of generated tokens that came from the draft
        # (vs being generated by the target verifying)
        accept = n_from_draft / len(sd_tokens) if sd_tokens else 0
        speedup = t_base / t_sd

        # Output quality check — should match
        out_base = tokenizer.decode(base_tokens[:20])
        out_sd = tokenizer.decode(sd_tokens[:20])
        match = "✓" if out_base == out_sd else "✗"

        print(f"  base:  {base_tps:.1f} tok/s  ({len(base_tokens)} tok in {t_base*1000:.0f} ms)")
        print(f"  sd:    {sd_tps:.1f} tok/s  ({len(sd_tokens)} tok in {t_sd*1000:.0f} ms)")
        print(f"  accept: {n_from_draft}/{len(sd_tokens)} = {accept:.1%}  speedup: {speedup:.2f}×  output_match: {match}")
        if match == "✗":
            print(f"    base: {out_base!r}")
            print(f"    sd:   {out_sd!r}")
        print()

        results.append({
            "prompt": prompt,
            "base_tok_s": base_tps,
            "sd_tok_s": sd_tps,
            "speedup": speedup,
            "acceptance": accept,
            "n_tokens": len(sd_tokens),
            "output_match": out_base == out_sd,
        })

    # Summary
    print("=" * 70)
    print(f"{'':35s}  {'mean':>8s}  {'median':>8s}  {'min':>8s}  {'max':>8s}")
    for key in ["base_tok_s", "sd_tok_s", "speedup", "acceptance"]:
        vals = [r[key] for r in results]
        label = {"base_tok_s": "baseline tok/s", "sd_tok_s": "SD tok/s",
                 "speedup": "speedup", "acceptance": "acceptance rate"}[key]
        if key == "acceptance":
            print(f"{label:35s}  {statistics.mean(vals):>7.1%}  {statistics.median(vals):>7.1%}  {min(vals):>7.1%}  {max(vals):>7.1%}")
        elif key == "speedup":
            print(f"{label:35s}  {statistics.mean(vals):>8.2f}  {statistics.median(vals):>8.2f}  {min(vals):>8.2f}  {max(vals):>8.2f}")
        else:
            print(f"{label:35s}  {statistics.mean(vals):>8.1f}  {statistics.median(vals):>8.1f}  {min(vals):>8.1f}  {max(vals):>8.1f}")
    print("=" * 70)

    match_count = sum(1 for r in results if r["output_match"])
    print(f"Output match (first 20 tokens): {match_count}/{len(results)}")

    avg_accept = statistics.mean([r["acceptance"] for r in results])
    avg_speedup = statistics.mean([r["speedup"] for r in results])
    print()
    print(f"DECISION GATE:")
    if avg_accept >= 0.6:
        print(f"  ✓ HIGH acceptance ({avg_accept:.1%}) — proceed to Phase 1 (ANE draft bridge)")
    elif avg_accept >= 0.4:
        print(f"  ~ MODERATE acceptance ({avg_accept:.1%}) — try larger draft (Gemma-3-1B) or proceed")
    else:
        print(f"  ✗ LOW acceptance ({avg_accept:.1%}) — try Qwen3/Llama pairs or custom training")
    print(f"  Average speedup: {avg_speedup:.2f}×")


if __name__ == "__main__":
    main()
